// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Staj_Proje.DaTa;

#nullable disable

namespace Staj_Proje.Migrations
{
    [DbContext(typeof(dbconTexT))]
    [Migration("20250716194732_migeklendi")]
    partial class migeklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Staj_Proje.EnTiTy.CommenT", b =>
                {
                    b.Property<int>("commeTID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("commeTID"));

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleTed")
                        .HasColumnType("bit");

                    b.Property<string>("admnbackcommenT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("auThorname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("auThorsurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("projecTID1")
                        .HasColumnType("int");

                    b.Property<DateTime>("wriTeTime")
                        .HasColumnType("datetime2");

                    b.HasKey("commeTID");

                    b.HasIndex("projecTID1");

                    b.ToTable("commenT");
                });

            modelBuilder.Entity("Staj_Proje.EnTiTy.ConTacT", b =>
                {
                    b.Property<int>("conTacTID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("conTacTID"));

                    b.Property<DateTime?>("AnswercommenT")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firsTname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lasTname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("senTTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("subjecT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("conTacTID");

                    b.ToTable("conTacT");
                });

            modelBuilder.Entity("Staj_Proje.EnTiTy.Home", b =>
                {
                    b.Property<int>("mainpage_abouTmeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mainpage_abouTmeID"));

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TiTle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopprojecT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mypicTureURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shortabouTme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subTiTle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updaTeTime")
                        .HasColumnType("datetime2");

                    b.HasKey("mainpage_abouTmeID");

                    b.ToTable("mainpage_abouTme");
                });

            modelBuilder.Entity("Staj_Proje.EnTiTy.MyprojecT", b =>
                {
                    b.Property<int>("projecTID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("projecTID"));

                    b.Property<int?>("Homemainpage_abouTmeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleTed")
                        .HasColumnType("bit");

                    b.Property<string>("TiTle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caTegory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("demolink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descripTion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("giThublink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("projecTImageURl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shorTdecripTion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updaTeTime")
                        .HasColumnType("datetime2");

                    b.HasKey("projecTID");

                    b.HasIndex("Homemainpage_abouTmeID");

                    b.ToTable("myprojecT");
                });

            modelBuilder.Entity("Staj_Proje.EnTiTy.CommenT", b =>
                {
                    b.HasOne("Staj_Proje.EnTiTy.MyprojecT", "projecTID")
                        .WithMany("commenT")
                        .HasForeignKey("projecTID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("projecTID");
                });

            modelBuilder.Entity("Staj_Proje.EnTiTy.MyprojecT", b =>
                {
                    b.HasOne("Staj_Proje.EnTiTy.Home", null)
                        .WithMany("mylasTprojecT")
                        .HasForeignKey("Homemainpage_abouTmeID");
                });

            modelBuilder.Entity("Staj_Proje.EnTiTy.Home", b =>
                {
                    b.Navigation("mylasTprojecT");
                });

            modelBuilder.Entity("Staj_Proje.EnTiTy.MyprojecT", b =>
                {
                    b.Navigation("commenT");
                });
#pragma warning restore 612, 618
        }
    }
}
